replicaCount: 1

image:
  repository: lion-cr.kr.ncr.ntruss.com/lion-app
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets:
  - name: regcred
nameOverride: ""
fullnameOverride: ""

service:
  type: LoadBalancer
  port: 80

dbService:
  type: NodePort
  port: 5432

containerPort: 8000

configMap:
  django:
    DJANGO_SETTINGS_MODULE: "lion_app.settings.staging"

secret:
  db:
    POSTGRES_DB: lionforum
    POSTGRES_USER: lion
    POSTGRES_PASSWORD: tiger
    POSTGRES_PORT: "5432"
  django:
    DJANGO_SECRET_KEY: django-insecure-9)1ht#_fpvwt&(+f0i4^sf#l=z^jc=+&b!n@o=iv38pu1vn(#&
