apiVersion: v1
kind: Pod
metadata:
  name: {{ include "lion.db.fullname" . }}
  labels:
    {{- include "lion.db.labels" . | nindent 4 }}
spec:
  containers:
    - name: {{ include "lion.db.fullname" . }}
      image: postgres:13
      env:
        - name: PGDATA
          value: "/var/lib/postgresql/data/k8s"
      envFrom:
        - secretRef:
            name: {{ include "lion.db.fullname" . }}
      ports:
        - containerPort: {{ .Values.dbService.port }}
      volumeMounts:
        - mountPath: "/var/lib/postgresql/data"
          name: postgres-data
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"
  volumes:
    - name: postgres-data
      persistentVolumeClaim:
        claimName: {{ include "lion.db.fullname" . }}

