apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lion.db.fullname" . }}
type: Opaque
data:
  {{- range $key, $val := .Values.secret.db }}
    {{ $key }}: {{ $val | b64enc | quote }}
  {{- end }}
