# Generated by Django 4.2.4 on 2023-09-19 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sns', '0002_post_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
